config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
               :path=> '',
               :path_names=> {:sign_in=> 'login', :sign_out=> 'logout', :edit=> 'profile'},
               :controllers=> {:registrations=> 'registrations',
                               :confirmations => 'confirmations',
                               :omniauth_callbacks => 'omniauth_callbacks'
                             }
resources :annouces, path:'annonce' do

            resources :reviews, only: [:create, :destroy]

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'pages#home'
# chemin d'accès de la méthode show du controller User
resources :users, only: [:show]
resources :rooms, path:'annonces' do

            resources :reservations, only: [:create]
            resources :reviews, only: [:create, :destroy]

end
resources :photos
resources :conversations, only: [:index, :create] do

       resources :messages, only: [:index, :create]

 end
get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'
get :your_trips, to: 'reservations#your_trips' , path: 'mes_voyages'
get :your_reservations , to: 'reservations#your_reservations', path: 'mes_reservations'
get '/search' => 'pages#search'
end

app/views/pages/home.html.erb
<div class="row">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
         <!-- Indicators -->
         <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
              <img src="https://www.phoenixdatacom.com/wp-content/uploads/2016/10/HoC-1200x380.jpg" >
                <div class="carousel-caption">
                    <h2>Réservez des logements uniques et vivez votre destination comme un habitant</h2>
                </div>
            </div>
            <div class="item">
              <img src="http://bcca.eu/wp-content/uploads/2016/04/top_bcca-1200x380.jpg" >
                <div class="carousel-caption">
                    <h2>Réservez des logements uniques et vivez votre destination comme un habitant</h2>
                </div>
            </div>
            <div class="item">
              <img src="http://ayurvedaholistique.com/wordpresskevin/wp-content/uploads/2015/07/Cap-Sounion-Grece-1200x380.jpg" >
                <div class="carousel-caption">
                    <h2>Réservez des logements uniques et vivez votre destination comme un habitant</h2>
                </div>
            </div>
            <div class="item">
              <img src="http://presstomsk.ru/wp-content/uploads/2016/02/DSC7062-1200x380.jpg" >
                <div class="carousel-caption">
                    <h2>Réservez des logements uniques et vivez votre destination comme un habitant</h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
</div>
</div>
<br>
<%= form_tag search_path, method: :get do %>
    <div class="row">
        <div class="col-md-6">
            <%= text_field_tag :search, params[:search], placeholder: "Où? Destination, ville, adresse",
            class:"form-control" %>
        </div>
        <div class="col-md-2">
            <%= text_field_tag :start_date, params[:start_date], placeholder:"Arrivée", class:"form-control" %>
        </div>
        <div class="col-md-2">
            <%= text_field_tag :end_date, params[:end_date], placeholder:"Départ", class:"form-control" %>
        </div>
        <div class="col-md-2">
            <%= submit_tag "Rechercher", class:"btn btn-primary" %>
        </div>
    </div>
<% end %>
<br>
<hr>
<br>
<div class="row">
    <div class="col-md-4">
        <h1>Logements</h1>
    </div>
</div
<div class="row">
    <% @rooms.each_slice(1) do |group| %>
        <div class="col-md-4">
          <% group.each do |room | %>
              <div class="panel panel-default">
                  <div class="panel-heading preview">
                      <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                  </div>
                  <div class="panel-body">
                      <p class="home-link"><b><%= link_to room.price, room_path(room) %> TND - <%= link_to room.room_type, room_path(room) %> - <%= link_to pluralize(room.bed_room, "lit"), room_path(room) %></b>
                      <br><%= link_to room.listing_name, room_path(room) %></p>
                  </div>
              </div>
          <% end %>
        </div>
    <% end %>


</div>
<script>
    $(function() {
        $('#start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        var newdate = new Date($("#start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#end_date').datepicker("option","minDate", newdate);
                    }
        });
        $('#end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        $('#start_date').datepicker("option", "maxDate", selected);
                    }
        });
    })
</script>

app/views/pages/search.html.erb
<div id="wrapper">
    <div id="sidebar">
        <div id="widget">
                          <script>
                            function initMap() {
                              <% if @arrRooms.length > 0 %>
                                  var uluru = {lat: <%= @arrRooms[0].latitude %>, lng: <%= @arrRooms[0].longitude %>};
                                  var map = new google.maps.Map(document.getElementById('widget'), {
                                    zoom: 13,
                                    center: uluru
                                  });
                              <% else %>
                                  var uluru = {lat: 48.866667, lng: 2.333333};
                                  var map = new google.maps.Map(document.getElementById('widget'), {
                                    zoom: 4,
                                    center: uluru
                                  });
                              <% end %>

                              <% @arrRooms.each do |room| %>
                              var marker = new google.maps.Marker({
                                position: {lat: <%= room.latitude %>, lng: <%= room.longitude %>},
                                map: map,
                                title: "<%= room.listing_name %>"
                              });
                              <% end %>
                            }
                          </script>
                          <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDBWzH7VJTGL_5cQgGVBi7wqDc-BhQRLeY&callback=initMap">                          </script>
                  </div>

    </div>
    <div id="article">
        <div class="row">
            <div class="col-md-12">
                <%= search_form_for @search, url: search_path do |f| %>
                    <div class="row">
                        <div class="col-md-3">
                            <%= text_field_tag :start_date, params[:start_date], placeholder:"Arrivée", class:"form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= text_field_tag :end_date, params[:end_date], placeholder:"Départ", class:"form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= f.text_field :price_gteq, placeholder: "Budget min", class: "form-control" %>
                        </div>
                        <div class="col-md-3">
                            <%= f.text_field :price_lteq, placeholder: "Budget max", class: "form-control" %>
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]","logement de luxe" %> logement de luxe
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]","logement simple" %> logement simple
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]","logement traditionnel" %> logement traditionnel
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label>Voyageurs ?</label>
                                <%= f.select :accommodate_gteq, [["1 voyageur",1],["2 voyageurs",2],["3 voyageurs",3], ["4 voyageurs",4] ,["5 voyageurs",5],["6 voyageurs",6]], prompt:"A sélectionner...",class:"form-control" %>
                            </div>
                        </div>

                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label>Chambres ?</label>
                                <%= f.select :bed_room_gteq, [["1",1],["2",2],
                                ["3",3], ["4",4]], prompt:"A sélectionner...",
                                class:"form-control" %>
                            </div>
                        </div>

                        <div class="col-md-4 select">
                            <div class="form-group">
                                <label>Salles de bain ?</label>
                                <%= f.select :bath_room_gteq, [["1",1],["2",2],
                                ["3",3], ["4",4]], prompt:"A sélectionner...",
                                class:"form-control" %>
                            </div>
                        </div>
                    </div>

                    <hr>

                    <div class="row">
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_wifi_eq]", true %> Wifi
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_tv_eq]", true %> Télévision
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_closet_eq]", true %> Penderie
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_shampoo_eq]", true %> Shampoing
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_kitchen_eq]", true %> Cuisine
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_swimming_pool_eq]", true %> piscine
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_heating_eq]", true %> Chauffage
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_air_eq]", true %> Climatisation
                        </div>
                    </div>

                    <br>

                    <center><div class="row">
                        <%= f.submit "Rechercher", class:"btn btn-primary" %>
                    </div></center>


                <% end %>

                <hr>



                <div class="row">
                    <% if @arrRooms.empty? %>
                        Aucune annonce ne correpond à votre recherche.
                    <% else %>
                        <% @arrRooms.each_slice(1) do |group| %>
                        <div class="col-md-6">
                          <% group.each do |room| %>
                                <div class="panel panel-default">
                                    <div class="panel-heading preview">
                                        <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                                    </div>
                                    <div class="panel-body">
                                        <p class="home-link"><b>   <%= image_tag avatar_url(room.user), class:"img-circle avatar-small" %>
                                        <%= link_to room.listing_name, room %>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                        <% end %>
                    <% end %>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
        $('#start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        var newdate = new Date($("#start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#end_date').datepicker("option","minDate", newdate);
                    }
        })

        $('#end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '3m',
                    onSelect: function(selected) {
                        $('#start_date').datepicker("option", "maxDate", selected);
                    }
        });
    })
</script>

<script>

 $(document).ready(function(){

           $("#sidebar").stick_in_parent({offset_top: 20});

 });

 </script>