config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
               :path=> '',
               :path_names=> {:sign_in=> 'login', :sign_out=> 'logout', :edit=> 'profile'},
               :controllers=> {:registrations=> 'registrations',
                               :confirmations => 'confirmations',
                               :omniauth_callbacks => 'omniauth_callbacks'
                             }
resources :annouces, path:'annonce' do

            resources :reviews, only: [:create, :destroy]

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'pages#home'
# chemin d'accès de la méthode show du controller User
resources :users, only: [:show]
resources :rooms, path:'annonces' do

            resources :reservations, only: [:create]
            resources :reviews, only: [:create, :destroy]

end
resources :photos
resources :conversations, only: [:index, :create] do

       resources :messages, only: [:index, :create]

 end
get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'
get :your_trips, to: 'reservations#your_trips' , path: 'mes_voyages'
get :your_reservations , to: 'reservations#your_reservations', path: 'mes_reservations'
get '/search' => 'pages#search'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
 has_many :photos, dependent: :destroy
 has_many :reservations, dependent: :destroy
 has_many :reviews, dependent: :destroy
                 validates :home_type, presence: true

                 validates :room_type, presence: true

                 validates :accommodate, presence: true

                 validates :bed_room, presence: true

                 validates :bath_room, presence: true

                 validates :listing_name, presence: true, length: {maximum: 75}

                 validates :summary, presence: true, length: {maximum: 600}

                 validates :address, presence: true

                 validates :price, numericality: { only_integer: true, greater_than: 5 }

                 geocoded_by :address


 after_validation :geocode, if: :address_changed?

 def average_rating

         reviews.count == 0 ? 0 : reviews.average(:star).round(2)

  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
before_action :set_room, only: [:show, :edit, :update]
before_action :authenticate_user!, except: [:show]
before_action :require_same_user, only: [:edit, :update]


      def index

         @rooms = current_user.rooms

 end
       def new

      @room = current_user.rooms.build

      end

      def create

        @room = current_user.rooms.build(room_params)

        if @room.save
          if params[:images]

             params[:images].each do |i|

        @room.photos.create(image: i)
              end

           end

@photos = @room.photos
redirect_to edit_room_path(@room), notice:"Votre logement a été ajouté"

        else

             render :new

        end

      end

       def show
       @photos = @room.photos
       @reviews = @room.reviews

              if current_user

                    @booked = Reservation.where("room_id = ? AND user_id = ?", @room.id, current_user.id).present?

                    @hasReview = @reviews.find_by(user_id: current_user.id)

              end
        end

      def edit
        @photos = @room.photos

       end

      def update

         if @room.update(room_params)
           if params[:images]

                  params[:images].each do |i|

                       @room.photos.create(image: i)

                  end

            end
            @photos = @room.photos
            redirect_to edit_room_path(@room), notice:"Modification enregistrée..."

         else

             render :edit

         end
       end



        private

              def set_room

                  @room = Room.find(params[:id])

           end

       def room_params

          params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room,
                                       :listing_name, :summary, :address, :is_wifi, :is_tv, :is_closet,
                                       :is_shampoo, :is_swimming_pool, :is_heating, :is_air, :is_kitchen, :price,
                                       :active)

     end
     def require_same_user

          if current_user.id != @room.user_id

               flash[:danger] = "Vous n'avez pas le droit de modifier cette page"

               redirect_to root_path

          end

 end

end

app/views/rooms/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        Devenez un locataire
    </div>
    <div class="panel-body">
        <div class="container">

            <%= form_for @room, html: {multipart: true} do |f| %>
           <%= render 'shared/errors' %>
            <div class="row">
                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Genre d'habitation</label>
                            <%= f.select :home_type, [["Maison","Maison"], ["Appartement","Appartement"],
                            ["villa", "villa"]], id: "home_type",
                            prompt: "A sélectionner...", class: "form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Type de logement</label>
                            <%= f.select :room_type, [["logement de luxe","logement de luxe"], ["logement simple","logement simple"],
                            ["logement traditionnel","logement traditionnel"]],
                            prompt: "A sélectionner...", class: "form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label> Combien de voyageurs ?</label>
                            <%= f.select :accommodate, [["1 voyageur",1], ["2 voyageurs",2],
                            ["3 voyageurs", 3], ["4 voyageurs",4], ["5 voyageurs",5], ["6 voyageurs",6]],
                            prompt: "A sélectionner...", class: "form-control" %>
                        </div>
                    </div>

                </div>

            <div class="row">
                    <div class="col-md-4 select">
                    <div class="form-group">
                        <label>Chambre(s)</label>
                        <%= f.select :bed_room, [["1 chambre",1], ["2 chambres",2],
                        ["3 chambres", 3], ["4 chambres ou plus",4]],
                        prompt: "Sélectionner le nombre", class: "form-control" %>
                    </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Salle(s) de bain</label>
                            <%= f.select :bath_room, [["1 salle de bain",1], ["2 salles de bain",2],
                            ["3 salles de bain", 3], ["4 salles de bain ou plus",4]],
                            prompt: "Sélectionner le nombre", class: "form-control" %>
                        </div>
                    </div>
                </div>

            <div class="row">
                    <div class="form-group">
                        <label>Donnez un nom au logement</label>
                        <%= f.text_field :listing_name, placeholder: "Titre de l'annonce", class: "form-control" %>
                    </div>
                </div>

            <div class="row">
                    <div class="form-group">
                        <label>Résumé</label>
                        <%= f.text_area :summary, rows:4, placeholder: "Décrivez le décor, l'ambiance, ce qui se trouve à proximité, etc...",
                        class: "form-control" %>
                    </div>
                </div>

            <div class="row">
                    <div class="form-group">
                        <label>Adresse</label>
                        <%= f.text_field :address, placeholder: "Où est situé votre logement ?", class: "form-control" %>
                    </div>
                </div>
                <div class="row">

                       <div class="col-md-4">

                           <div class="form-group">

                                 <span class="btn btn-default btn-file">

                                 <i class = "fa fa-cloud-upload-alt"></i> Téléchargez vos photos !

                                 <%= file_field_tag "images[]", type: :file, multiple: true %>

                                 </span>

                           </div>

                       </div>

                 </div>

                 <div id="photos"><%= render 'photos/list' %></div>


            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <%= f.check_box :is_wifi %> Wifi
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_tv %> Télévision
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_closet %> Penderie/Commode
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_shampoo %> Shampoing
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <%= f.check_box :is_kitchen %> Cuisine
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_swimming_pool %> piscine
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_heating %> Chauffage
                    </div>

                    <div class="form-group">
                        <%= f.check_box :is_air %> Climatisation
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Prix par nuit</label>
                        <div class="input-group">
                                <%= f.text_field :price, placeholder: "ex: 45 TND", class: "form-control" %>
                                <div class="input-group-addon">TND</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <%= f.check_box :active %> Annonce active
                </div>
            </div>

            <div class="actions">
                      <%= f.submit "Je valide mon annonce", class: "btn btn-primary"%>
            </div>
            <% end %>

        </div>
    </div>
</div>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row">

      <div class="col-md-3">

            <ul class="sidebar-list">

                   <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path,class: "sidebar-link active" %></li>
                   <li class="sidebar-item"><%= link_to "Mes réservations",your_reservations_path, class:"sidebar-link" %></li>
                   <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link" %></li>
            </ul>

       </div>

       <div class="col-md-9">

            <div class="panel panel-default">

                 <div class="panel-heading">Mes annonces

                 </div>


                <div class="panel-body">

                      <% @rooms.each do |room| %>

                         <div class="row">

                                 <div class="col-md-2">

                                      <%= image_tag room.photos[0].image.url(:thumb)  if room.photos.length > 0 %>

                                 </div>

                                 <div class="col-md-7">

                                        <h4><%= link_to room.listing_name, room %></h4>

                                 </div>

                                 <div class="col-md-3 right">

                                     <%= link_to "Mettre à jour", edit_room_path(room),
                                                                  class: "btn btn-primary" %>

                                 </div>

                        </div>

                        <hr>

                   <% end %>

               </div>

           </div>

     </div>

 </div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="panel panel-default">
    <div class="panel-body">


        <div class="row">
            <div class="col-md-12">
                <%= image_tag @photos[0].image.url(), class:"img-responsive" if @photos.length >0 %>
            </div>
        </div>

        <br>


        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-3 text-center">
                       <%= link_to user_path(@room.user) do %>
                        <%= image_tag avatar_url(@room.user), class:"img-circle avatar-large" %>
                        <% end %>
                        <br>
                        <br>
                        <%= @room.user.fullname %>
                    </div>
                    <div class="col-md-9">
                        <h4><%= @room.listing_name %></h4>
                        <a href="#map", class="sidebar-link"><%= @room.address %></a> <a href="#average_rating", class="sidebar-link"><span id="average_rating_header"></span> <%= @reviews.count %></a>
                        <div class="row text-center row-space-1">
                            <div class="col-sm-3">
                                <i class="fa fa-home fa-2x"></i>
                            </div>
                            <div class="col-sm-3">
                                <i class="fa fa-users fa-2x"></i>
                            </div>
                            <div class="col-sm-3">
                                <i class="fa fa-bed fa-2x"></i>
                            </div>
                            <div class="col-sm-3">
                                <i class="fa fa-bath fa-2x"></i>
                            </div>
                        </div>
                        <div class="row text-center">
                            <div class="col-sm-3">
                                <%= @room.home_type %>
                            </div>
                            <div class="col-sm-3">
                                <%= @room.accommodate %> <%= @room.accommodate > 1 ? "Voyageurs" : "Voyageur" %>
                            </div>
                            <div class="col-sm-3">
                                <%= @room.bed_room %> <%= @room.bed_room > 1 ? "Lits" : "Lit" %>
                            </div>
                            <div class="col-sm-3">
                                <%= @room.bath_room %> <%= @room.bath_room > 1 ? "Salles de bain" : "Salle de bain" %>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <h2>A propos de ce logement</h2>
                        <p><%= @room.summary %></p>
                    </div>
                </div>

                <br>


                <div class="row">
                    <div class="col-md-2">
                        <p>Equipements</p>
                    </div>
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-6">
                                <ul class="equipments">
                                    <li class="<%= 'text-line-through' if !@room.is_wifi %>">Wifi</li>
                                    <li class="<%= 'text-line-through' if !@room.is_tv %>">Télévision</li>
                                    <li class="<%= 'text-line-through' if !@room.is_closet %>">Penderie/Commode</li>
                                    <li class="<%= 'text-line-through' if !@room.is_shampoo %>">Shampoing</li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul class="equipments">
                                    <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Cuisine</li>
                                    <li class="<%= 'text-line-through' if !@room.is_swimming_pool %>">piscine</li>
                                    <li class="<%= 'text-line-through' if !@room.is_heating %>">Chauffage</li>
                                    <li class="<%= 'text-line-through' if !@room.is_air %>">Climatisation</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
            <div class="col-md-4">

                <%= render 'reservations/form' %>
            </div>
        </div>

        <br>
        <hr>



        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                  <!-- Indicators -->
                    <% if @photos %>
                        <% @photos.each do |photo| %>
                          <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="<%= photo.id %>" class="active"></li>
                          </ol>
                        <% end %>
                    <% end %>


                  <div class="carousel-inner" role="listbox">
                    <% if @photos %>
                    <% @photos.each do |photo| %>
                    <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                      <%= image_tag photo.image.url() %>
                    </div>
                    <% end %>
                    <% end %>

                  </div>


                  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Précédent</span>
                  </a>
                  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Suivant</span>
                  </a>
                </div>
            </div>
        </div>

        <br>
        <hr>


        <div class="row">
            <div class="col-md-12">
                <h3><%= pluralize(@reviews.count, 'Commentaire') %> <span id="average_rating"></span></h3>
                <div class="container">
                    <div>
                        <%= render 'reviews/form' if @booked && !@hasReview %>
                    </div>
                    <div>
                        <%= render 'reviews/list' %>
                    </div>
                </div>
            </div>
        </div>

        <br>

            <div class="row">
            <div class="col-md-12">
                <div id="map"></div>

                <style>
                   #map {
                    height: 400px;
                    width: 100%;
                   }
                </style>

                <script>
                  function initMap() {
                    var uluru = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
                    var map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 15,
                      center: uluru
                    });
                    var marker = new google.maps.Marker({
                      position: uluru,
                      map: map
                    });

                  }

                </script>

                <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDBWzH7VJTGL_5cQgGVBi7wqDc-BhQRLeY&callback=initMap">
                </script>
            </div>
        </div>


        <h3>A proximité...</h3>
         <div class="row">
             <% for room in @room.nearbys(2).limit(3) %>
             <div class="col-md-4">
                 <div class="panel panel-default">
                     <div class="panel-heading preview">
                         <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                     </div>
                     <div class="panel-body">
                         <%= link_to room.listing_name, room %><br>
                         (à <%= (room.distance*1.6).round(2) %> km)
                     </div>
                 </div>
             </div>
             <% end %>
        </div>


    </div>
</div>


        <script>
            $('#average_rating').raty({
                path: '/assets',
                readOnly: true,
                score: <%= @room.average_rating %>
            });
        </script>

        <script>
            $('#average_rating_header').raty({
                path: '/assets',
                readOnly: true,
                score: <%= @room.average_rating %>
            });
        </script>