config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
               :path=> '',
               :path_names=> {:sign_in=> 'login', :sign_out=> 'logout', :edit=> 'profile'},
               :controllers=> {:registrations=> 'registrations',
                               :confirmations => 'confirmations',
                               :omniauth_callbacks => 'omniauth_callbacks'
                             }
resources :annouces, path:'annonce' do

            resources :reviews, only: [:create, :destroy]

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'pages#home'
# chemin d'accès de la méthode show du controller User
resources :users, only: [:show]
resources :rooms, path:'annonces' do

            resources :reservations, only: [:create]
            resources :reviews, only: [:create, :destroy]

end
resources :photos
resources :conversations, only: [:index, :create] do

       resources :messages, only: [:index, :create]

 end
get '/preload' => 'reservations#preload'
get '/preview' => 'reservations#preview'
get :your_trips, to: 'reservations#your_trips' , path: 'mes_voyages'
get :your_reservations , to: 'reservations#your_reservations', path: 'mes_reservations'
get '/search' => 'pages#search'
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'CoinLocation', root_path, { :class=>"navbar-brand" } %>
        </div>
        <div id="navbar" class="navbar-collapse collapse right">
          <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>

  <div class="search">

  <span class="fa fa-search"></span>

  <%= text_field_tag :search, params[:search], placeholder: "Rechercher", class: "form-control" %>

  </div>

  <% end %>

           <ul class="nav navbar-nav navbar-right">
             <li>

              <%= link_to new_room_path do %>

              <i class="fa fa-home fa-lg"></i> Devenez un locataire
              <% end %>

              </li>

              <li>

            <%= link_to conversations_path do %><i class="fa fa-envelope fa-lg"></i> Messages<% end %>

             </li>

            <% if (!user_signed_in?) %>

                 <li><%= link_to 'Inscription', new_user_registration_path %></li>

                  <li><%= link_to 'Connexion', new_user_session_path %></li>

            <% else %>

                <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>
                <%= current_user.fullname %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Mes annonces", rooms_path %></li>
                  <li><%= link_to "Mes reservation", your_reservations_path %></li>
                    <li><%= link_to "Mes voyages", your_trips_path %></li>

                <li><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Déconnexion', destroy_user_session_path,method: :delete %></li>
              </ul>
            </li>
            <% end %>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoinLocation</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag "https://js.stripe.com/v2/" %>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <%= favicon_link_tag 'favicon.ico' %>


  </head>

  <body>
<%= render 'layouts/navigation' %>
  <%= render 'shared/message' %>
  <div class="container" >  <%= yield %> </div>
  </body>
</html>